[package]
name = "cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "skylow"
path = "src/main.rs"

[dependencies]
bumpalo.workspace = true
compiler.workspace = true
baselang.workspace = true
mir.workspace = true
