[package]
name = "skylow-mir"
version.workspace = true
edition.workspace = true

[dependencies]
skylow-baselang.workspace = true

[dev-dependencies]
bumpalo.workspace = true
datatest-stable.workspace = true

[[test]]
name = "compile"
harness = false
