[package]
name = "jit"
version.workspace = true
edition.workspace = true

[dependencies]
libc.workspace = true
mir.workspace = true

[dev-dependencies]
bumpalo.workspace = true
datatest-stable.workspace = true
baselang.workspace = true

[[test]]
name = "execute"
harness = false
