[package]
name = "baselang"
version.workspace = true
edition.workspace = true

[dependencies]
bumpalo.workspace = true
common.workspace = true
parser.workspace = true

[dev-dependencies]
datatest-stable.workspace = true

[[test]]
name = "lower"
harness = false
