[package]
name = "skylow-baselang"
version.workspace = true
edition.workspace = true

[dependencies]
bumpalo.workspace = true
skylow-common.workspace = true
skylow-parser.workspace = true

[dev-dependencies]
datatest-stable.workspace = true

[[test]]
name = "lower"
harness = false
